### ISSUE TITLE
Experimental result

### ISSUE THREAD

**Issue by 1292765944** [xmyqsh/FPN#1]
Cool code! I wonder whether you have reimplemented the exact results of the FPN paper?

Best!
guangxing

**Comment by Yc174** [comment]
Have you trained this ?Can you tell me the results? @1292765944

**Comment by xmyqsh** [comment]
I'm starting training...

**Comment by chl916185** [comment]
When I was loading the trained model，I met this error：
Traceback (most recent call last):
  File "./faster_rcnn/test_net.py", line 44, in <module>
    network = get_network(network_name)
  File "./faster_rcnn/../lib/networks/factory.py", line 19, in get_network
    return FPN_test()
  File "./faster_rcnn/../lib/networks/FPN_test.py", line 26, in __init__
    self.setup()
  File "./faster_rcnn/../lib/networks/FPN_test.py", line 356, in setup
    .fc(n_classes, relu=False, name='cls_score'))
  File "./faster_rcnn/../lib/networks/network.py", line 34, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "./faster_rcnn/../lib/networks/network.py", line 407, in fc
    regularizer=self.l2_regularizer(cfg.TRAIN.WEIGHT_DECAY))
  File "./faster_rcnn/../lib/networks/network.py", line 97, in make_var
    return tf.get_variable(name, shape, initializer=initializer, trainable=trainable, regularizer=regularizer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 639, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable cls_score/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "./faster_rcnn/../lib/networks/network.py", line 97, in make_var
    return tf.get_variable(name, shape, initializer=initializer, trainable=trainable, regularizer=regularizer)
  File "./faster_rcnn/../lib/networks/network.py", line 407, in fc
    regularizer=self.l2_regularizer(cfg.TRAIN.WEIGHT_DECAY))
  File "./faster_rcnn/../lib/networks/network.py", line 34, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)

The reason is that：
#========= RCNN ============
        .fc(n_classes, relu=False, name='cls_score'))
in lib/networks/FPN_test.py.
@xmyqsh

**Comment by xmyqsh** [comment]
@1292765944 @Yc174 @chl916185 

train result,   rpn_loss is on the fly...
What is the reason that may cause rpn_loss not converge, do you think ?

speed: 0.412s / iter
image: 2008_000307.jpg iter: 199870 / 200000, total loss: 21.4851, rpn_loss_cls: 1.2544, rpn_loss_box: 19.9337, loss_cls: 0.2095, loss_box: 0.0876, lr: 0.0000
00
speed: 0.401s / iter
image: 2008_005319.jpg iter: 199880 / 200000, total loss: 11.8511, rpn_loss_cls: 1.3227, rpn_loss_box: 10.2611, loss_cls: 0.2030, loss_box: 0.0643, lr: 0.0000
00
speed: 0.406s / iter
image: 006483.jpg iter: 199890 / 200000, total loss: 25.3140, rpn_loss_cls: 1.1014, rpn_loss_box: 24.0750, loss_cls: 0.1176, loss_box: 0.0201, lr: 0.000000
speed: 0.395s / iter
image: 002967.jpg iter: 199900 / 200000, total loss: 10.4668, rpn_loss_cls: 1.5063, rpn_loss_box: 8.6171, loss_cls: 0.2443, loss_box: 0.0990, lr: 0.000000
speed: 0.397s / iter
image: 2011_001198.jpg iter: 199910 / 200000, total loss: 14.9206, rpn_loss_cls: 1.4058, rpn_loss_box: 13.2595, loss_cls: 0.2015, loss_box: 0.0537, lr: 0.000000
speed: 0.380s / iter
image: 2008_003645.jpg iter: 199920 / 200000, total loss: 19.0740, rpn_loss_cls: 1.2057, rpn_loss_box: 17.1077, loss_cls: 0.5278, loss_box: 0.2328, lr: 0.000000
speed: 0.426s / iter
image: 005811.jpg iter: 199930 / 200000, total loss: 10.8934, rpn_loss_cls: 1.4540, rpn_loss_box: 9.0603, loss_cls: 0.2846, loss_box: 0.0945, lr: 0.000000
speed: 0.439s / iter
image: 2009_003860.jpg iter: 199940 / 200000, total loss: 14.3258, rpn_loss_cls: 1.6082, rpn_loss_box: 12.5498, loss_cls: 0.1635, loss_box: 0.0044, lr: 0.000000
speed: 0.388s / iter
image: 2011_000556.jpg iter: 199950 / 200000, total loss: 22.7038, rpn_loss_cls: 1.2282, rpn_loss_box: 20.8446, loss_cls: 0.3576, loss_box: 0.2734, lr: 0.000000
speed: 0.397s / iter
image: 2008_004585.jpg iter: 199960 / 200000, total loss: 11.1179, rpn_loss_cls: 1.3557, rpn_loss_box: 9.2402, loss_cls: 0.3512, loss_box: 0.1708, lr: 0.000000
speed: 0.346s / iter
image: 2008_000393.jpg iter: 199970 / 200000, total loss: 11.2609, rpn_loss_cls: 1.7995, rpn_loss_box: 8.7590, loss_cls: 0.4851, loss_box: 0.2173, lr: 0.000000
speed: 0.371s / iter
image: 2011_003081.jpg iter: 199980 / 200000, total loss: 10.4372, rpn_loss_cls: 1.4303, rpn_loss_box: 8.8616, loss_cls: 0.1440, loss_box: 0.0013, lr: 0.000000
speed: 0.342s / iter
image: 2008_007069.jpg iter: 199990 / 200000, total loss: 19.8492, rpn_loss_cls: 1.3173, rpn_loss_box: 18.3676, loss_cls: 0.1637, loss_box: 0.0005, lr: 0.000000
speed: 0.356s / iter

**Comment by chl916185** [comment]
the lr is 0.000000,why？
@xmyqsh

**Comment by 1292765944** [comment]
@xmyqsh I met similar problem. It is not easy to converge using the params in FPN paper. such as 800 pixels of the shorter side, including anchor boxes that are outside the image.
