### ISSUE TITLE
stuck in loading the resnet50

### ISSUE THREAD

**Issue by helxsz** [xmyqsh/FPN#10]
I am using two 970 to run the network, it just get stuck in loading the Resnet50.npy, maybe the memory is too small, but I suspect it will be stuck in a later stage than stuck in loading the Resnet50 anyway

```
2017-08-16 09:00:28.165008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1 
2017-08-16 09:00:28.165016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y Y 
2017-08-16 09:00:28.165028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y Y 
2017-08-16 09:00:28.165033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0)
2017-08-16 09:00:28.165036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 970, pci bus id: 0000:06:00.0)
Computing bounding-box regression targets...

19.63user 1.20system 0:25.18elapsed 82%CPU (0avgtext+0avgdata 1314772maxresident)k
583592inputs+3008outputs (159major+346781minor)pagefaults 0swaps
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading pretrained model weights from data/pretrain_model/Resnet50.npy
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 407, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 164, in train_model
    raise 'Check your pretrained model {:s}'.format(self.pretrained_model)
TypeError: exceptions must be old-style classes or derived from BaseException, not str
Command exited with non-zero status 1
19.63user 1.20system 0:25.18elapsed 82%CPU (0avgtext+0avgdata 1314772maxresident)k
583592inputs+3008outputs (159major+346781minor)pagefaults 0swaps
```

**Comment by wellingtonyl** [comment]
1. raise 'Check your pretrained model {:s}'.format(self.pretrained_model)  -->
raise Exception('Check your pretrained model {:s}'.format(self.pretrained_model))

2. check your Resnet50.npy, if it is in data/pretrain_model/

**Comment by Vijayshree12** [comment]
@helxsz will you please provide me a code about how to load resnet50.npy file?
