### ISSUE TITLE
Encounter this error: tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by Kongsea** [xmyqsh/FPN#26]
When I run train_net.py, I have met the following error:

> Traceback (most recent call last):
>   File "faster_rcnn/train_net.py", line 26, in <module>
>     from lib.networks.factory import get_network
>   File "faster_rcnn/../lib/networks/__init__.py", line 8, in <module>
>     from .FPN_train import FPN_train
>   File "faster_rcnn/../lib/networks/FPN_train.py", line 9, in <module>
>     from .network import Network
>   File "faster_rcnn/../lib/networks/network.py", line 5, in <module>
>     from ..roi_pooling_layer import roi_pooling_op as roi_pool_op
>   File "faster_rcnn/../lib/roi_pooling_layer/__init__.py", line 7, in <module>
>     import roi_pooling_op
>   File "faster_rcnn/../lib/roi_pooling_layer/roi_pooling_op.py", line 5, in <module>
>     _roi_pooling_module = tf.load_op_library(filename)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: faster_rcnn/../lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

What's the reason? Is there anybody who will give some advice?
Thank you.

**Comment by Kongsea** [comment]
After I clone this repository, I first open a terminal in FPN folder, and `cd lib`, then I run `make` to compile it.
Are these steps correct?

**Comment by Kongsea** [comment]
I have googled the problem, and find [one solution](https://github.com/smallcorgi/Faster-RCNN_TF/issues/25). Then I added `-D_GLIBCXX_USE_CXX11_ABI=0` in g++ complie line in make.sh file and re-run make.
However, that solution did not work.

**Comment by Kongsea** [comment]
Finally, uninstalling tensorflow 1.4 and installing tensorflow 1.3 and adding `-D_GLIBCXX_USE_CXX11_ABI=0` solved this problem.
