### ISSUE TITLE
How to run test_net?

### ISSUE THREAD

**Issue by dongmingyang** [xmyqsh/FPN#3]
Hi
Thx for your excellent job! I'm a new learner and it benefits me a lot.
I notice that there is no test_net.py in FPN/faster_rcnn/
So, could u tell me how to run a test?
I neet to know the mAP of my task.
Thx again :)
@xmyqsh

**Comment by chl916185** [comment]
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 85, in __call__
    ret = func(*args)
  File "./faster_rcnn/../lib/rpn_msr/anchor_target_layer.py", line 144, in anchor_target_layer
    gt_argmax_overlaps = overlaps.argmax(axis=0) # G
ValueError: attempt to get argmax of an empty sequence

When I met the above training VOC2007 error, how do you solve？@
@xmyqsh @BestSongEver

**Comment by chl916185** [comment]
how do you solve this problem？
@BestSongEver

**Comment by BestSongEver** [comment]
Sorry, i never met this issue. But i just checked it on google. 
It might caused by "Because the ratio of images width and heights is too small or large" 
Hope it helpful. @chl916185

**Comment by chl916185** [comment]
Thank you, it is really inappropriate three pictures, I didn't use them, problem solved, but How to run test_net.py? I met the same problem with you.
Traceback (most recent call last):
  File "./faster_rcnn/test_net.py", line 83, in <module>
    network = get_network(args.network_name)
  File "./faster_rcnn/../lib/networks/factory.py", line 19, in get_network
    return FPN_test()
  File "./faster_rcnn/../lib/networks/FPN_test.py", line 25, in __init__
    self.setup()
  File "./faster_rcnn/../lib/networks/FPN_test.py", line 231, in setup
    .fc(n_classes, relu=False, name='cls_score')
  File "./faster_rcnn/../lib/networks/network.py", line 34, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "./faster_rcnn/../lib/networks/network.py", line 391, in fc
    dim = dim*d
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
@BestSongEver

**Comment by xmyqsh** [comment]
@chl916185 @BestSongEver 
hi there,
I've updated anchors filtering logic in proposal target layer  to cope with the problem encountered in low h/w ratio images

I will check the test_net latter

**Comment by chl916185** [comment]
(<tf.Tensor 'rpn_rois/rpn_rois_P2:0' shape=(?, 5) dtype=float32>, <tf.Tensor 'rpn_rois/rpn_rois_P3:0' shape=(?, 5) dtype=float32>,           <tf.Tensor 'rpn_rois/rpn_rois_P4:0' shape=(?, 5) dtype=float32>, <tf.Tensor 'rpn_rois/rpn_rois_P5:0' shape=(?, 5) dtype=float32>)
[<tf.Tensor 'P2/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'P3/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf          .Tensor 'P4/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'P5/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, (<tf.Te          nsor 'rpn_rois/rpn_rois_P2:0' shape=(?, 5) dtype=float32>, <tf.Tensor 'rpn_rois/rpn_rois_P3:0' shape=(?, 5) dtype=float32>, <tf.Te          nsor 'rpn_rois/rpn_rois_P4:0' shape=(?, 5) dtype=float32>, <tf.Tensor 'rpn_rois/rpn_rois_P5:0' shape=(?, 5) dtype=float32>)]
Traceback (most recent call last):
  File "./faster_rcnn/test_net.py", line 78, in <module>
    network = get_network(args.network_name)
  File "./faster_rcnn/../lib/networks/factory.py", line 19, in get_network
    return FPN_test()
  File "./faster_rcnn/../lib/networks/FPN_test.py", line 25, in __init__
    self.setup()
  File "./faster_rcnn/../lib/networks/FPN_test.py", line 354, in setup
    .fc(n_classes, relu=False, name='cls_score')
  File "./faster_rcnn/../lib/networks/network.py", line 34, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "./faster_rcnn/../lib/networks/network.py", line 405, in fc
    regularizer=self.l2_regularizer(cfg.TRAIN.WEIGHT_DECAY))
  File "./faster_rcnn/../lib/networks/network.py", line 96, in make_var
    return tf.get_variable(name, shape, initializer=initializer, trainable=trainable, regularizer=regularizer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 639, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable cls_score/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined           at:

  File "./faster_rcnn/../lib/networks/network.py", line 96, in make_var
    return tf.get_variable(name, shape, initializer=initializer, trainable=trainable, regularizer=regularizer)
  File "./faster_rcnn/../lib/networks/network.py", line 405, in fc
    regularizer=self.l2_regularizer(cfg.TRAIN.WEIGHT_DECAY))
  File "./faster_rcnn/../lib/networks/network.py", line 34, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
