### ISSUE TITLE
different shape error when training now data

### ISSUE THREAD

**Issue by wang-tf** [xmyqsh/FPN#31]
When I traing my data using
`nohup ./experiments/scripts/FPN_end2end.sh 0 FPN pascal_voc2007 --set RNG_SEED 42 TRAIN.SCALES "[800]" > FPN.log 2>&1 &`
I got this trouble
```
ignore bn4f_branch2a offset
ignore res5a_branch2c weights
ignore res5a_branch2b weights
ignore res5a_branch2a weights
ignore res3d_branch2b weights
ignore res3d_branch2c weights
ignore res3d_branch2a weights
./faster_rcnn/../lib/fast_rcnn/bbox_transform.py:61: RuntimeWarning: overflow encountered in exp
  pred_w = np.exp(dw) * widths[:, np.newaxis]
./faster_rcnn/../lib/fast_rcnn/bbox_transform.py:61: RuntimeWarning: overflow encountered in multiply
  pred_w = np.exp(dw) * widths[:, np.newaxis]
./faster_rcnn/../lib/fast_rcnn/bbox_transform.py:62: RuntimeWarning: overflow encountered in exp
  pred_h = np.exp(dh) * heights[:, np.newaxis]
./faster_rcnn/../lib/fast_rcnn/bbox_transform.py:62: RuntimeWarning: overflow encountered in multiply
  pred_h = np.exp(dh) * heights[:, np.newaxis]
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 407, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 277, in train_model
    bbox_pred = bbox_pred * np.tile(self.bbox_stds, (bbox_pred.shape[0], 1)) + \
ValueError: operands could not be broadcast together with shapes (128,84) (128,8) 
Command exited with non-zero status 1
13.00user 2.02system 0:14.48elapsed 103%CPU (0avgtext+0avgdata 2385504maxresident)k
0inputs+3096outputs (0major+371289minor)pagefaults 0swaps
```
I don't know how to fix it.

**Comment by wang-tf** [comment]
I fixed it when I changed NCLASSES in experiments/cfgs/FPN_end2end.yml
